language: php

php:
- 7.1
- 7.2
- 7.3

env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
- composer update --prefer-source --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - php vendor/bin/php-coveralls -v -x clover.xml -o clover.json

notifications:
  email: false
